apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-service
  labels:
    app: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
      - name: demo
        image: gcr.io/${PROJECT_ID}/demo-service:latest
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
          requests:
            memory: "128Mi"
            cpu: "250m"
        # Enable Cloud Monitoring scraping
        env:
        - name: PORT
          value: "8080"